apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: workspace
  name: workspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workspace
  template:
    metadata:
      labels:
        app: workspace
    spec:
      volumes:
        - name: vol-workspace-pvc
          persistentVolumeClaim:
            claimName: workspace-pvc
      containers:
        - image: nextcloud:19
          name: nextcloud
          env:
            - name: SQLITE_DATABASE
              value: ""
            - name: NEXTCLOUD_ADMIN_USER
              value: "eoepca"
            - name: NEXTCLOUD_ADMIN_PASSWORD
              value: "telespazio"
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: '"*"'
          volumeMounts:
            - mountPath: "/var/www/html"
              name: vol-workspace-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: workspace
  name: workspace
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31999
  selector:
    app: workspace
  type: NodePort
